/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.kelompoka3.form;

import com.kelompoka3.koneksi.koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LAB_MMC
 */
public class formHistory extends javax.swing.JPanel {
    DefaultTableModel tabel = new DefaultTableModel();
//    
    

    /** Creates new form formHistory */
    public formHistory() {
        initComponents();
        tableformhistory();
//        tampilkan_tabelLP();
        Date now = new Date();
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy");
        String tgl = simpleDateFormat.format(now), data;

       
//        koneksi conn = new koneksi();
        
        tbr.addTableStyle(jScrollPane1);
        
//        
    }
    private void tableformhistory() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No Faktur");
        model.addColumn("Id Barang");
        model.addColumn("jumlah Barang");
        model.addColumn("Harga Barang");
        model.addColumn("Nama Barang");  
        model.addColumn("Tanggal"); 
        String cari = txt_cari.getText();
        try {
            String sql = "SELECT detailpenjualan.noFaktur,detailpenjualan.idBarang,detailpenjualan.jumlahBarang,"
                    + "detailpenjualan.hargaBarang,detailpenjualan.namaBarang,faktur.tanggal "
                    + "FROM detailpenjualan INNER JOIN faktur ON detailpenjualan.noFaktur=faktur.noFaktur "
                    + "WHERE detailpenjualan.noFaktur LIKE'%"+cari+"%' OR "
                    + "detailpenjualan.idBarang LIKE'%"+cari+"%' OR "
                    + "detailpenjualan.jumlahBarang LIKE'%"+cari+"%' OR "
                    + "detailpenjualan.hargaBarang LIKE'%"+cari+"%' OR "
                    + "detailpenjualan.namaBarang LIKE'%"+cari+"%' OR "
                    + "faktur.tanggal LIKE'%"+cari+"%' ORDER BY tanggal DESC";
            
            java.sql.Connection conn = (Connection) koneksi.koneksi();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            while (res.next()) {
                model.addRow(new Object[]{"#" + res.getString(1), res.getString(2),
                    res.getString(3), res.getString(4), res.getString(5),res.getString(6) });
            }
            tbr.setModel(model);
        } catch (SQLException e) {
        }

    }
    
    private void tampilkan_tabelLP() {
        
        String tanggal = ((JTextField)date1.getDateEditor().getUiComponent()).getText();
        String tanggal2 = ((JTextField)date2.getDateEditor().getUiComponent()).getText();
        
        
       try {
            String sql1 = "SELECT detailpenjualan.noFaktur,detailpenjualan.idBarang,detailpenjualan.jumlahBarang,"
                    + "detailpenjualan.hargaBarang,detailpenjualan.namaBarang,faktur.tanggal FROM detailpenjualan "
                    + "JOIN faktur ON detailpenjualan.noFaktur=faktur.noFaktur "
                    + "WHERE faktur.tanggal BETWEEN '"+tanggal+"' AND '" +tanggal2+"' ORDER BY tanggal ASC ";
                
                
            java.sql.Connection conn = (Connection) koneksi.koneksi();
            java.sql.PreparedStatement pst1 = conn.prepareStatement(sql1);
            java.sql.ResultSet rs = pst1.executeQuery(sql1);
            DefaultTableModel model = (DefaultTableModel)tbr.getModel();
            model.setRowCount(0);
            

            while (rs.next()) {
                    model.addRow(new Object[]{ rs.getString(1), rs.getString(2),
                    rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6) });
            }
            tbr.setModel(model);
        } catch (SQLException ex) {
        }

    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbr = new com.kelompoka3.swing.Table();
        buttonCustom1 = new com.kelompoka3.swing.ButtonCustom();
        txt_cari = new javax.swing.JTextField();
        date1 = new com.toedter.calendar.JDateChooser();
        date2 = new com.toedter.calendar.JDateChooser();
        btnn = new com.kelompoka3.swing.ButtonCustom();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tbr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbr);

        buttonCustom1.setText("Search");
        buttonCustom1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonCustom1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCustom1MouseClicked(evt);
            }
        });

        date1.setDateFormatString("yyyy-MM-dd");

        date2.setDateFormatString("yyyy-MM-dd");

        btnn.setText("Tampilkan");
        btnn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1075, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(buttonCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(date2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(date2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCustom1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCustom1MouseClicked
        // TODO add your handling code here:
       tableformhistory();
       
    }//GEN-LAST:event_buttonCustom1MouseClicked

    private void btnnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnMouseClicked
        // TODO add your handling code here:
        tampilkan_tabelLP();
//    tableformhistory();
    }//GEN-LAST:event_btnnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.kelompoka3.swing.ButtonCustom btnn;
    private com.kelompoka3.swing.ButtonCustom buttonCustom1;
    private com.toedter.calendar.JDateChooser date1;
    private com.toedter.calendar.JDateChooser date2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.kelompoka3.swing.Table tbr;
    private javax.swing.JTextField txt_cari;
    // End of variables declaration//GEN-END:variables

}
